version: '3.1'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - './nginx/config/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/ssl:/etc/nginx/ssl'
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
  pengha-api:
    image: yonghochoi/pengha-api
    container_name: pengha-api
    restart: always
    ports:
      - '8000:8000'
