version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
  pengha-api:
    image: yonghochoi/pengha-api
    container_name: pengha-api
    restart: always
    ports:
      - '8000:8000'
